from typing import Union
import openai
from pydantic import Field
from atomic_agents.agents.base_agent import BaseAgent, BaseAgentConfig
from atomic_agents.lib.base.base_io_schema import BaseIOSchema
from atomic_agents.lib.components.agent_memory import AgentMemory
from atomic_agents.lib.components.system_prompt_generator import SystemPromptGenerator, SystemPromptContextProviderBase

from orchestration_agent.tools.searxng_search import (
    SearxNGSearchTool,
    SearxNGSearchToolConfig,
    SearxNGSearchToolInputSchema,
    SearxNGSearchToolOutputSchema,
)
from orchestration_agent.tools.calculator import (
    CalculatorTool,
    CalculatorToolConfig,
    CalculatorToolInputSchema,
    CalculatorToolOutputSchema,
)
from orchestration_agent.tools.rag_search import ( # Updated import path
    RAGSearchTool,
    RAGSearchToolConfig,
    RAGSearchToolInputSchema,
    RAGSearchToolOutputSchema
)

import instructor
from datetime import datetime
from dotenv import load_dotenv

load_dotenv()  # Load environment variables from .env file

########################
# INPUT/OUTPUT SCHEMAS #
########################
class OrchestratorInputSchema(BaseIOSchema):
    """Input schema for the Orchestrator Agent. Contains the user's message to be processed."""

    chat_message: str = Field(..., description="The user's input message to be analyzed and responded to.")


class OrchestratorOutputSchema(BaseIOSchema):
    """Combined output schema for the Orchestrator Agent. Contains the tool to use and its parameters."""

    tool: str = Field(..., description="The tool to use: 'search', 'calculator', or 'rag'")
    tool_parameters: Union[SearxNGSearchToolInputSchema, CalculatorToolInputSchema, RAGSearchToolInputSchema] = Field(
        ..., description="The parameters for the selected tool"
    )


class FinalAnswerSchema(BaseIOSchema):
    """Schema for the final answer generated by the Orchestrator Agent."""

    final_answer: str = Field(..., description="The final answer generated based on the tool output and user query.")


#######################
# AGENT CONFIGURATION #
#######################
class OrchestratorAgentConfig(BaseAgentConfig):
    """Configuration for the Orchestrator Agent."""

    searxng_config: SearxNGSearchToolConfig
    calculator_config: CalculatorToolConfig
    rag_config: RAGSearchToolConfig


#####################
# CONTEXT PROVIDERS #
#####################
class CurrentDateProvider(SystemPromptContextProviderBase):
    def __init__(self, title):
        super().__init__(title)
        self.date = datetime.now().strftime("%Y-%m-%d")

    def get_info(self) -> str:
        return f"Current date in format YYYY-MM-DD: {self.date}"


######################
# ORCHESTRATOR AGENT #
######################
orchestrator_agent = BaseAgent(
    BaseAgentConfig(
        client=instructor.from_openai(openai.OpenAI()),
        model="gpt-4o-mini",
        system_prompt_generator=SystemPromptGenerator(
            background=[
                "You are an Orchestrator Agent that decides between using a search tool, a calculator tool, or a RAG tool based on user input.",
                "Use the search tool for queries requiring external factual information, current events, or specific data.",
                "Use the calculator tool for mathematical calculations and expressions.",
                "Use the RAG tool for questions about internal documentation, knowledge base, or project-specific information. The user will explicitly state if they want to use the RAG tool.",
            ],
            output_instructions=[
                "Analyze the input to determine whether it requires a web search, a calculation, or searching in the knowledge base.",
                "For search queries, use the 'search' tool and provide 1-3 relevant search queries.",
                "For calculations, use the 'calculator' tool and provide the mathematical expression to evaluate.",
                "For questions about internal documentation or knowledge where the user specifies to use RAG, use the 'rag' tool and provide the question.",
                "Format the output using the appropriate schema.",
            ],
        ),
        input_schema=OrchestratorInputSchema,
        output_schema=OrchestratorOutputSchema,
    )
)

# Register the current date provider
orchestrator_agent.register_context_provider("current_date", CurrentDateProvider("Current Date"))


def execute_tool(
    searxng_tool: SearxNGSearchTool, calculator_tool: CalculatorTool, rag_tool: RAGSearchTool, orchestrator_output: OrchestratorOutputSchema
) -> Union[SearxNGSearchToolOutputSchema, CalculatorToolOutputSchema, RAGSearchToolOutputSchema]:
    if orchestrator_output.tool == "search":
        # Ensure the parameters are of the correct type for the tool
        if not isinstance(orchestrator_output.tool_parameters, SearxNGSearchToolInputSchema):
            raise ValueError(f"Invalid parameters for search tool: {orchestrator_output.tool_parameters}")
        return searxng_tool.run(orchestrator_output.tool_parameters)
    elif orchestrator_output.tool == "calculator":
        if not isinstance(orchestrator_output.tool_parameters, CalculatorToolInputSchema):
            raise ValueError(f"Invalid parameters for calculator tool: {orchestrator_output.tool_parameters}")
        return calculator_tool.run(orchestrator_output.tool_parameters)
    elif orchestrator_output.tool == "rag":
        if not isinstance(orchestrator_output.tool_parameters, RAGSearchToolInputSchema):
            raise ValueError(f"Invalid parameters for RAG tool: {orchestrator_output.tool_parameters}")
        return rag_tool.run(orchestrator_output.tool_parameters)
    else:
        raise ValueError(f"Unknown tool: {orchestrator_output.tool}")


#################
# EXAMPLE USAGE #
#################
if __name__ == "__main__":
    import os
    from dotenv import load_dotenv
    from rich.console import Console
    from rich.panel import Panel
    from rich.syntax import Syntax

    load_dotenv()

    # Set up the OpenAI client
    client = instructor.from_openai(openai.OpenAI(api_key=os.getenv("OPENAI_API_KEY")))

    # Initialize the tools
    searxng_tool = SearxNGSearchTool(SearxNGSearchToolConfig(base_url="http://localhost:8080", max_results=3)) # Replace with your SearxNG instance
    calculator_tool = CalculatorTool(CalculatorToolConfig())
    # Configure RAG tool - create a knowledge_base directory in the SRE-agent folder or update path
    # Ensure OPENAI_API_KEY is set in .env or environment
    knowledge_base_dir = os.path.join(os.path.dirname(__file__), "..", "knowledge_base_sre")
    os.makedirs(knowledge_base_dir, exist_ok=True)
    # Add some dummy files to knowledge_base_sre for testing
    with open(os.path.join(knowledge_base_dir, "sre_handbook.md"), "w") as f:
        f.write("# SRE Handbook\n\nThis document contains best practices for Site Reliability Engineering.\n\n## Chapter 1: Introduction\nSLOs, SLIs, Error Budgets.")
    with open(os.path.join(knowledge_base_dir, "incident_response.txt"), "w") as f:
        f.write("Incident Response Plan:\n1. Identify\n2. Contain\n3. Eradicate\n4. Recover\n5. Lessons Learned.")
        
    rag_tool_config = RAGSearchToolConfig(
        docs_dir=knowledge_base_dir,
        persist_dir=os.path.join(os.path.dirname(__file__), "..", "sre_chroma_db"),
        recreate_collection_on_init=True # Set to False after first run if you want to persist DB
    )
    rag_tool = RAGSearchTool(config=rag_tool_config)

    # Initialize Rich console
    console = Console()

    # Print the full system prompt
    console.print(Panel(orchestrator_agent.system_prompt_generator.generate_prompt(), title="System Prompt", expand=False))
    console.print("\n")

    # Example inputs
    inputs = [
        "Who won the Nobel Prize in Physics in 2024?",
        "Please calculate the sine of pi/3 to the third power",
        "Use RAG to tell me about SLOs from the SRE handbook",
        "Use RAG to find the incident response plan",
    ]

    for user_input in inputs:
        console.print(Panel(f"[bold cyan]User Input:[/bold cyan] {user_input}", expand=False))

        # Create the input schema
        input_schema = OrchestratorInputSchema(chat_message=user_input)

        # Print the input schema
        console.print("\n[bold yellow]Generated Input Schema:[/bold yellow]")
        input_syntax = Syntax(str(input_schema.model_dump_json(indent=2)), "json", theme="monokai", line_numbers=True)
        console.print(input_syntax)

        # Run the orchestrator to get the tool selection and input
        orchestrator_output = orchestrator_agent.run(input_schema)

        # Print the orchestrator output
        console.print("\n[bold magenta]Orchestrator Output:[/bold magenta]")
        orchestrator_syntax = Syntax(
            str(orchestrator_output.model_dump_json(indent=2)), "json", theme="monokai", line_numbers=True
        )
        console.print(orchestrator_syntax)

        # Run the selected tool
        response = execute_tool(searxng_tool, calculator_tool, rag_tool, orchestrator_output)

        # Print the tool output
        console.print("\n[bold green]Tool Output:[/bold green]")
        output_syntax = Syntax(str(response.model_dump_json(indent=2)), "json", theme="monokai", line_numbers=True)
        console.print(output_syntax)

        console.print("\n" + "-" * 80 + "\n")

        orchestrator_agent.output_schema = FinalAnswerSchema
        orchestrator_agent.memory.add_message("system", response)
        final_answer = orchestrator_agent.run(input_schema)
        console.print(f"\n[bold blue]Final Answer:[/bold blue] {final_answer.final_answer}")
        orchestrator_agent.output_schema = OrchestratorOutputSchema

        # Reset the memory after each response
        orchestrator_agent.memory = AgentMemory()
